---
baseURL: 
languageCode: en-us
DefaultContentLanguage: en
title: Aligner | Translate 10X faster | Online free platform.
# theme: hugo-fresh
# googleAnalytics: UA-138300699-1
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  BookMenuBundle: "/menu"
  openGraph: true
  description: Translate 10 times faster with Aligner. Free collaboration tool.
  navbarlogo:
    image: logo-new.png
    link: "/en"
    alt: Aligner
  font:
    name: Poppins
    sizes:
    - 400
    - 600
Languages:
  en:
    contentDir: content/english
    home: Home
    languageCode: en-us
    languageName: English
    weight: "1"
  et:
    contentDir: content/estonian
    home: Kodu
    languageCode: et
    languageName: Eesti keeles
    weight: "2"
    title: Aligner | Tasuta online t천lkeplatvorm.
    params:
      BookMenuBundle: "/men체체"
      openGraph: true
      description: Tasuta t천lkimine ja mitmekeelse sisu haldamine.
      navbarlogo:
        link: "/et"
        alt: Aligner home page logo
        image: logo-new.png
      font:
        name: Poppins
        sizes:
        - 400
        - 600